### ISSUE TITLE
Do you have a plan to upload the source code?

### ISSUE THREAD

**Issue by OTL** [sipeed/MaixSense_ROS#1]
You have already published the source as a zip [here](https://dl.sipeed.com/shareURL/MaixSense/MaixSense_A010/software_pack/SDK).

Do you have a plan to upload it to GitHub?

Or can we upload your code?
I can't find the license (TODO).

Thank you for your great product!!!

**Comment by taorye** [comment]
We had published.

Thank you for your reminding.

**Comment by OTL** [comment]
thank you for your great work!!!
